site_name: Container 101

pages:
    - 'Introduction': 'index.md'
    - 'Getting Started': 'ramp-up.md'
    - 'Configure Lab': 'setup.md'
    - 'Application Overview': 'overview.md'
    - 'Application Deploy': 'deploy.md'
